# Generated by Django 2.0 on 2018-01-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelAuthor',
        ),
        migrations.DeleteModel(
            name='ModelComment',
        ),
        migrations.DeleteModel(
            name='ModelDemo',
        ),
        migrations.DeleteModel(
            name='ModelDummyUser',
        ),
        migrations.DeleteModel(
            name='ModelPost',
        ),
    ]
